### ISSUE TITLE
New Cordex domain (#1) Arctic (possibly named as ARC-11)

### ISSUE THREAD

**Issue by berg0138** [WCRP-CORDEX/domain-tables#14]
Hi Jesus / github managers.
In fall 2023, two new polar Cordex domains have been approved. These domains, however, have not reached this github repository. The new Arctic domain specifications are:

For the Arctic:
A) For rotated polar RCMs (in rotated coordinates):
Rotated Pole: 0.0; 6.55: (which is similar to the current domain)
nlon = 577
nlat = 582
west  =   -29.900
south =   -24.200
east  =    27.700
north =    33.900
dx of 0.1 degrees (11 km - which is deviating from most CORDEX domains)
The southern, eastern, and northern boundaries are near similar to the existing ARC12 and ARC50 domains, but the western boundary is moved 7 degrees further over Russia. 

B) For non-rotated polar RCMs (in actual coordinates):
TLC lon/lat:    41.236   51.120
CNB lon/lat:     1.986   62.631
TRC lon/lat:   320.634   52.534
CWB lon/lat:    91.777   60.200
CPD lon/lat:   147.918   87.936
CEB lon/lat:   267.835   62.384
BLC lon/lat:   137.572   47.629
CSB lon/lat:   178.038   59.231
BRC lon/lat:   220.333   49.074

Please contact Annette Rinke (annette.rinke@awi.de) or one of the other Polar CORDEX POCs for confirmation if needed.

**Comment by gnikulin** [comment]
Yes, I've got updated configuration for both Arctic and Antarctica domains from Annette but only actual coordinates (non-rotated ones) have been updated in https://github.com/WCRP-CORDEX/domain-tables/blob/main/CORDEX-CMIP6_domain_boundaries.csv  I think updating the rotated coordinates is still pending.

Willem Jan, could you also provide the updated  rotated coordinates for Antarctica ? 

Regarding the domain acronym (ARC-12 or ARC-11), the CORDEX-CMIP6 archiving specs define that "The domain acronym is
 ‘domain name’-‘resolution’, where ‘resolution’ is the nearest grid spacing in km of the 3 resolutions used in CORDEX-CMIP5 and
CORDEX-CMIP6 (50,25 and 12km)."

**Comment by berg0138** [comment]
It replaces the current domain. The groups listed to do ARC-12 simulations in the simulations table (AWI, HCLIMcom-METNo) also use this new domain.

**Comment by larsbuntemeyer** [comment]
One more question: Should we drop the `ARC-50` domain for the CMIP6 domains table then? It will become inconsistent with the new `ARC-12` and we usually had the implicit convention, that domains fit consistently into each other, having, e.g., same boundaries. This was usefull when domain resolutions are compared using regridding.

**Comment by berg0138** [comment]
Dear Lars, Nikulin: I could provide (after consulting the Polar CORDEX representatives) a revised version of the ARC-50 and ANT-50 domains. Would that also be an option?

**Comment by larsbuntemeyer** [comment]
I updated `ARC-12` in #20 and removed `ARC-50` for now.
 
@gnikulin From my calculation, 0.1° resolution fits more to 11 km resoltuion (11.132m) at the equator. Nevertheless, I set the `domain_id` to `ARC-12` although according to our [new convention](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/2), it should probably be `ARC-11`? Please let me know, if this should be adapted!

Concerning the `ARC-50` domain, i'm fine with removing it if there are no runs anyway. If you need a definition for some evaluation, it think it would make sense to have a domain that fits with new definition, e.g., having a 0.4° resolution (not 0.44°) so that grid cells exactly overlap like it used to be.

**Comment by gnikulin** [comment]
The CORDEX-CMIP6 archiving specs define that "The domain acronym is ‘domain name’-‘resolution’, where ‘resolution’ is the nearest grid spacing in km of the 3 resolutions used in CORDEX-CMIP5 and CORDEX-CMIP6 (50,25 and 12km)." and ARC-12 and ANT-12 are used in the CORDEX-CMIP6 simulations status.

The old configuration for "ANT-50" can also be deleted since the ANT domain has a new configuration.

**Comment by larsbuntemeyer** [comment]
Ok, then I'll close this, thanks everyone!

**Comment by berg0138** [comment]
Most thanks to you guys, for handing my request!
